project:
  type: website
  output-dir: docs

website:
  title: "Blog de Christian"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/cballejo/
      - icon: twitter-x
        href: http://x.com/chrisballejo
format:
  html:
    theme:
      light: zephyr
      dark:  darkly
    css: styles.css
    code-copy: true

editor: visual

